-- AlterTable
ALTER TABLE "Player" ADD COLUMN IF NOT EXISTS "dailyQuests" JSONB;
ALTER TABLE "Player" ADD COLUMN IF NOT EXISTS "lastChestClaimAt" TIMESTAMP(3);
ALTER TABLE "Player" ADD COLUMN IF NOT EXISTS "firstWinDate" TEXT;
ALTER TABLE "Player" ADD COLUMN IF NOT EXISTS "mysteryBoxesPending" INTEGER NOT NULL DEFAULT 0;
